// src/compiler/features/framework-codegen.ts
// Auto-generates React/Vue/Svelte/Solid components from style definitions

interface ComponentInfo {
  name: string;
  selector: string;
  styles: Record<string, any>;
  propsDefinition?: Record<string, any>;
  framework: 'react' | 'vue' | 'svelte' | 'solid' | 'auto';
}

export function detectFramework(): 'react' | 'vue' | 'svelte' | 'solid' {
  try { require.resolve('react/package.json'); return 'react'; } catch {}
  try { require.resolve('vue/package.json'); return 'vue'; } catch {}
  try { require.resolve('svelte/package.json'); return 'svelte'; } catch {}
  try { require.resolve('solid-js/package.json'); return 'solid'; } catch {}
  return 'react';
}

export function generateComponentCode(info: ComponentInfo): string {
  const framework = info.framework === 'auto' ? detectFramework() : info.framework;
  const safeName = info.name.replace(/[^a-zA-Z0-9_-]/g, '');
  if (!safeName) throw new Error('Invalid component name: ' + info.name);
  const cleanSelector = info.selector.replace(/^\./, '');
  
  switch (framework) {
    case 'react': {
      const props = info.propsDefinition
        ? Object.entries(info.propsDefinition)
            .filter(([k]) => /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(k))
            .map(([k, t]) => {
              const safeType = ['string', 'number', 'boolean', 'any', 'ReactNode', 'JSX.Element'].includes(t) ? t : 'any';
              return `  ${k}?: ${safeType};`;
            }).join('\n')
        : '  [key: string]: any;';
      return `// Auto-generated by ChainCSS
import React from 'react';
import styles from './${safeName}.class.js';
import './${safeName}.css';

export interface ${info.name}Props {
  className?: string;
  children?: React.ReactNode;
${props}
}

export const ${info.name}: React.FC<${info.name}Props> = ({ className, children, ...props }) => {
  const cn = [styles[${JSON.stringify(info.name)}], className].filter(Boolean).join(' ');
  return <div className={cn} {...props}>{children}</div>;
};
${info.name}.displayName = 'ChainCSS${info.name}';
export default ${info.name};
`;
    }
    case 'vue':
      return `<!-- Auto-generated by ChainCSS -->
<template>
  <component :is="tag" :class="combinedClass" v-bind="$attrs"><slot /></component>
</template>
<script>
import styles from './${safeName}.class.js';
import './${safeName}.css';
export default {
  name: 'ChainCSS${info.name}',
  props: { tag: { type: String, default: 'div' }, className: { type: String, default: '' } },
  computed: { combinedClass() { return [styles[${JSON.stringify(info.name)}], this.className].filter(Boolean).join(' '); } }
};
</script>`;
    case 'svelte':
      return `<!-- Auto-generated by ChainCSS -->
<script>
  import styles from './${safeName}.class.js';
  import './${safeName}.css';
  export let className = '';
  export let tag = 'div';
  $: combinedClass = [styles[${JSON.stringify(info.name)}], className].filter(Boolean).join(' ');
</script>
<svelte:element this={tag} class={combinedClass}><slot /></svelte:element>`;
    case 'solid':
      return `// Auto-generated by ChainCSS
import { splitProps } from 'solid-js';
import styles from './${safeName}.class.js';
import './${safeName}.css';
export function ${info.name}(props: any) {
  const [local, others] = splitProps(props, ['class', 'children']);
  const cn = () => [styles[${JSON.stringify(info.name)}], local.class].filter(Boolean).join(' ');
  return <div class={cn()} {...others}>{local.children}</div>;
}`;
    default:
      return generateComponentCode({ ...info, framework: 'react' });
  }
}

export type { ComponentInfo };