// src/compiler/features/framework-codegen.ts
// Auto-generates React/Vue/Svelte/Solid components from style definitions

import { createRequire } from 'module';

interface ComponentInfo {
  name: string;
  selector: string;
  styles: Record<string, any>;
  propsDefinition?: Record<string, any>;
  framework: 'react' | 'vue' | 'svelte' | 'solid' | 'auto';
}

/**
 * Safely sniff out package presence across dynamic CJS and ESM toolchains
 */
export function detectFramework(): 'react' | 'vue' | 'svelte' | 'solid' {
  let lookup: (path: string) => string;
  
  try {
    // ESM safe resolution check
    lookup = typeof require !== 'undefined' ? require.resolve : createRequire(import.meta.url).resolve;
  } catch {
    return 'react';
  }

  try { lookup('react'); return 'react'; } catch {}
  try { lookup('vue'); return 'vue'; } catch {}
  try { lookup('svelte'); return 'svelte'; } catch {}
  try { lookup('solid-js'); return 'solid'; } catch {}
  
  return 'react';
}

function toSafeComponentName(input: string): string {
  const cleaned = input.replace(/[^a-zA-Z0-9_-]/g, '').replace(/^[^a-zA-Z]+/, '')
  if (!cleaned) throw new Error('Invalid component name: ' + input)
  // my-button / my_button -> MyButton
  const pascal = cleaned.split(/[-_]+/).map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('')
  // guard reserved words
  const reserved = new Set(['class','default','export','import','function'])
  return reserved.has(pascal.toLowerCase()) ? `${pascal}Component` : pascal
}


export function generateComponentCode(info: ComponentInfo): string {
  const framework = info.framework === 'auto' ? detectFramework() : info.framework;
  
  const safeName = toSafeComponentName(info.name)
  if (!safeName) throw new Error('Invalid component name: ' + info.name);
  
  const cleanSelector = info.selector.replace(/^\./, '');
  const key = JSON.stringify(cleanSelector);

  switch (framework) {
    case 'react': {
      const props = info.propsDefinition
        ? Object.entries(info.propsDefinition)
            .filter(([k]) => /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(k))
            .map(([k, t]) => {
              const safeType = ['string', 'number', 'boolean', 'any', 'ReactNode', 'JSX.Element'].includes(t) ? t : 'any';
              return `  ${k}?: ${safeType};`;
            }).join('\n')
        : '  [key: string]: any;';
      return `// Auto-generated by ChainCSS
import React from 'react';
import styles from './${safeName}.class.js';
import './${safeName}.css';

export interface ${safeName}Props {
  tag?: React.ElementType;
  className?: string;
  children?: React.ReactNode;
${props}
}

export const ${safeName}: React.FC<${safeName}Props> = ({ tag: Component = 'div', className, children, ...props }) => {
  const cn = [styles[${key}], className].filter(Boolean).join(' ');
  return <Component className={cn} {...props}>{children}</Component>;
};
${safeName}.displayName = 'ChainCSS${safeName}';
export default ${safeName};
`;
    }
    case 'vue':
      return `<!-- Auto-generated by ChainCSS -->
<template>
  <component :is="tag" :class="combinedClass" v-bind="$attrs"><slot /></component>
</template>
<script>
import styles from './${safeName}.class.js';
import './${safeName}.css';
export default {
  name: 'ChainCSS${safeName}',
  props: { tag: { type: String, default: 'div' }, className: { type: String, default: '' } },
  computed: { combinedClass() { return [styles[${key}], this.className].filter(Boolean).join(' '); } }
};
</script>`;
    case 'svelte':
      return `<!-- Auto-generated by ChainCSS -->
<script>
  import styles from './${safeName}.class.js';
  import './${safeName}.css';
  export let className = '';
  export let tag = 'div';
  $: combinedClass = [styles[${key}], className].filter(Boolean).join(' ');
</script>
<svelte:element this={tag} class={combinedClass}><slot /></svelte:element>`;
    case 'solid':
      return `// Auto-generated by ChainCSS
import { Dynamic } from 'solid-js/web';
import styles from './${safeName}.class.js';
import './${safeName}.css';

export function ${safeName}(props: any) {
  // Backward compatible properties extraction supporting Solid versions < 1.4
  const tag = () => props.tag || 'div';
  const cn = () => [styles[${key}], props.class].filter(Boolean).join(' ');
  
  const restProps = () => {
    const { tag, class, children, ...rest } = props;
    return rest;
  };

  return <Dynamic component={tag()} class={cn()} {...restProps()}>{props.children}</Dynamic>;
}`;
    default:
      return generateComponentCode({ ...info, framework: 'react' });
  }
}

export type { ComponentInfo };