// src/compiler/features/framework-codegen.ts
// Auto-generates React/Vue/Svelte/Solid components from style definitions

import fs from "fs";
import { createRequire } from "module";
import path from "path";

interface ComponentInfo {
  name: string;
  selector: string;
  styles?: Record<string, any>;
  propsDefinition?: Record<string, any>;
  framework: "react" | "vue" | "svelte" | "solid" | "auto";
  cwd?: string;
}

const getMetaUrl = (): string => {
  try {
    if (typeof import.meta !== "undefined" && import.meta.url) {
      return import.meta.url;
    }
  } catch {}
  
  if (typeof __filename !== "undefined" && __filename) {
    return `file://${__filename}`;
  }
  
  return "";
};

/**
 * Safely sniffs framework presence from target project dependencies or module resolution.
 */
export function detectFramework(cwd: string = process.cwd()): "react" | "vue" | "svelte" | "solid" {
  // 1. Inspect target project's package.json first for accurate project-level detection
  try {
    const pkgPath = path.join(cwd, "package.json");
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
      const deps = { ...pkg.dependencies, ...pkg.devDependencies, ...pkg.peerDependencies };

      if (deps["solid-js"]) return "solid";
      if (deps["svelte"]) return "svelte";
      if (deps["vue"]) return "vue";
      if (deps["react"]) return "react";
    }
  } catch {}

  // 2. Fall back to module lookup resolution anchored to target cwd
  let lookup: (path: string) => string;
  try {
    const metaUrl = getMetaUrl();
    const req = metaUrl ? createRequire(metaUrl) : (typeof require !== "undefined" ? require : null);
    
    if (req) {
      lookup = (mod: string) => req.resolve(mod, { paths: [cwd] });
    } else {
      return "react";
    }
  } catch {
    return "react";
  }

  try { lookup("solid-js"); return "solid"; } catch {}
  try { lookup("svelte"); return "svelte"; } catch {}
  try { lookup("vue"); return "vue"; } catch {}
  try { lookup("react"); return "react"; } catch {}

  return "react";
}

const JS_RESERVED_WORDS = new Set([
  "break", "case", "catch", "class", "const", "continue", "debugger",
  "default", "delete", "do", "else", "enum", "export", "extends",
  "false", "finally", "for", "function", "if", "import", "in",
  "instanceof", "new", "null", "return", "super", "switch", "this",
  "throw", "true", "try", "typeof", "var", "void", "while", "with",
  "yield", "let", "static", "await", "package", "private", "protected",
  "public", "interface", "type", "object", "string", "number", "boolean",
  "component", "element"
]);

function toSafeComponentName(input: string): string {
  const cleaned = input
    .replace(/[^a-zA-Z0-9_-]/g, "")
    .replace(/^[^a-zA-Z]+/, "");
    
  if (!cleaned) throw new Error("Invalid component name: " + input);

  // my-button / my_button -> MyButton
  const pascal = cleaned
    .split(/[-_]+/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

  if (!pascal) throw new Error("Invalid component name: " + input);

  return JS_RESERVED_WORDS.has(pascal.toLowerCase()) ? `${pascal}Component` : pascal;
}

export function generateComponentCode(info: ComponentInfo): string {
  const framework =
    info.framework === "auto" ? detectFramework(info.cwd) : info.framework;

  const safeName = toSafeComponentName(info.name);
  const cleanSelector = info.selector.replace(/^\./, "");
  const key = JSON.stringify(cleanSelector);

  switch (framework) {
    case "react": {
      const props = info.propsDefinition
        ? Object.entries(info.propsDefinition)
            .filter(([k]) => /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(k))
            .map(([k, t]) => {
              let safeType = "any";
              if (t === "ReactNode") {
                safeType = "React.ReactNode";
              } else if (
                ["string", "number", "boolean", "any", "React.ReactNode", "JSX.Element"].includes(t)
              ) {
                safeType = t;
              }
              return `  ${k}?: ${safeType};`;
            })
            .join("\n")
        : "  [key: string]: any;";

      return `// Auto-generated by ChainCSS
import React from 'react';
import styles from './${safeName}.class.js';
import './${safeName}.css';

export interface ${safeName}Props {
  tag?: React.ElementType;
  className?: string;
  children?: React.ReactNode;
${props}
}

export const ${safeName}: React.FC<${safeName}Props> = ({ tag: Component = 'div', className, children, ...props }) => {
  const cn = [styles[${key}], className].filter(Boolean).join(' ');
  return <Component className={cn} {...props}>{children}</Component>;
};
${safeName}.displayName = 'ChainCSS${safeName}';
export default ${safeName};
`;
    }

    case "vue":
      return `<!-- Auto-generated by ChainCSS -->
<template>
  <component :is="tag" :class="combinedClass" v-bind="$attrs"><slot /></component>
</template>
<script>
import styles from './${safeName}.class.js';
import './${safeName}.css';
export default {
  name: 'ChainCSS${safeName}',
  props: { tag: { type: String, default: 'div' }, className: { type: String, default: '' } },
  computed: { combinedClass() { return [styles[${key}], this.className].filter(Boolean).join(' '); } }
};
</script>`;

    case "svelte":
      return `<!-- Auto-generated by ChainCSS -->
<script>
  import styles from './${safeName}.class.js';
  import './${safeName}.css';
  export let className = '';
  export let tag = 'div';
  $: combinedClass = [styles[${key}], className].filter(Boolean).join(' ');
</script>
<svelte:element this={tag} class={combinedClass}><slot /></svelte:element>`;

    case "solid":
      return `// Auto-generated by ChainCSS
import { Dynamic } from 'solid-js/web';
import styles from './${safeName}.class.js';
import './${safeName}.css';

export function ${safeName}(props: any) {
  const tag = () => props.tag || 'div';
  const cn = () => [styles[${key}], props.class || props.className].filter(Boolean).join(' ');
  
  const restProps = () => {
    const { tag, class: _c, className: _cn, children, ...rest } = props;
    return rest;
  };

  return <Dynamic component={tag()} class={cn()} {...restProps()}>{props.children}</Dynamic>;
}
export default ${safeName};
`;

    default:
      return generateComponentCode({ ...info, framework: "react" });
  }
}

export type { ComponentInfo };