// src/plugins/webpack.ts

import path from 'path';
import fs from 'fs';
import { ChainCSSCompiler } from '../core/compiler.js';
import type { ChainCSSConfig } from '../core/types.js';

export interface ChainCSSLoaderOptions {
  mode?: 'build' | 'runtime';
  atomic?: boolean;
  minify?: boolean;
  sourceMap?: boolean;
  outputDir?: string;
  verbose?: boolean;
  extractCSS?: boolean;
  hmr?: boolean;
  cacheKey?: string;
  framework?: 'react' | 'vue' | 'svelte' | 'solid' | 'auto';
}

interface LoaderContext {
  async: () => (err: Error | null, code?: string) => void;
  getOptions: () => ChainCSSLoaderOptions;
  resourcePath: string;
  context: string;
  cacheable: (flag: boolean) => void;
  addDependency: (file: string) => void;
  emitFile: (name: string, content: string, sourceMap?: any) => void;
  emitWarning: (warning: Error) => void;
  emitError: (error: Error) => void;
}

interface StyleExport {
  name: string;
  className: string;
}

// ============================================================================
// Utilities
// ============================================================================

function hashString(str: string): string {
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) + hash) + str.charCodeAt(i);
    hash = hash & hash;
  }
  return Math.abs(hash).toString(36);
}

function extractStyleExports(source: string): StyleExport[] {
  const exports: StyleExport[] = [];

  const constRegex = /const\s+(\w+)\s*=\s*(?:chain|\$)\(\s*\)\s*(?:\.\w+\([^)]*\)\s*)*\.\$el\(['"`]([^'"`]+)['"`]\)/g;
  let match;

  while ((match = constRegex.exec(source)) !== null) {
    exports.push({ name: match[1], className: match[2] });
  }

  const exportRegex = /export\s+const\s+(\w+)\s*=\s*(?:chain|\$)\(\s*\)\s*(?:\.\w+\([^)]*\)\s*)*\.\$el\(['"`]([^'"`]+)['"`]\)/g;
  while ((match = exportRegex.exec(source)) !== null) {
    exports.push({ name: match[1], className: match[2] });
  }

  return exports;
}

function generateRuntimeCode(
  source: string,
  styleExports: StyleExport[],
  resourcePath: string,
  options: ChainCSSLoaderOptions
): string {
  const hmrEnabled = options.hmr !== false && process.env.NODE_ENV !== 'production';
  const classMapping = styleExports.map(exp => `  ${exp.name}: '${exp.className}'`).join(',\n');

  return `
    // Generated by ChainCSS Webpack Loader (Runtime Mode)
    // Source: ${path.basename(resourcePath)}
    
    import { chain, enableDebug } from 'chaincss/runtime';
    
    ${hmrEnabled ? `if (process.env.NODE_ENV !== 'production') {
      enableDebug(${options.verbose || false});
    }` : ''}
    
    ${source}
    
    export const styles = {
    ${classMapping}
    };
    
    export default styles;
    
    ${hmrEnabled ? `
    if (module.hot) {
      module.hot.accept();
      module.hot.dispose(() => {
        const styleId = 'chaincss-${hashString(resourcePath)}';
        const style = document.getElementById(styleId);
        if (style) style.remove();
      });
    }
    ` : ''}
  `;
}

function generateProductionCode(
  css: string,
  styleExports: StyleExport[],
  resourcePath: string,
  options: ChainCSSLoaderOptions
): string {
  const classMapping = styleExports.map(exp => `  ${exp.name}: '${exp.className}'`).join(',\n');
  const escapedCSS = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');

  if (options.extractCSS) {
    return `
      // Generated by ChainCSS Webpack Loader (Build Mode - Extracted)
      // Source: ${path.basename(resourcePath)}
      
      export const styles = {
      ${classMapping}
      };
      
      export default styles;
    `;
  }

  return `
    // Generated by ChainCSS Webpack Loader (Build Mode - Injected)
    // Source: ${path.basename(resourcePath)}
    
    export const styles = {
    ${classMapping}
    };
    
    const css = \`${escapedCSS}\`;
    if (typeof document !== 'undefined' && css && css.trim()) {
      const styleId = 'chaincss-${hashString(resourcePath)}';
      let style = document.getElementById(styleId);
      if (!style) {
        style = document.createElement('style');
        style.id = styleId;
        style.setAttribute('data-chaincss', 'true');
        style.setAttribute('data-source', ${JSON.stringify(path.basename(resourcePath))});
        document.head.appendChild(style);
      }
      style.textContent = css;
    }
    
    export default styles;
  `;
}

// ============================================================================
// Compilation — uses ChainCSSCompiler directly, no child process
// ============================================================================

async function compileChainCSS(
  source: string,
  filePath: string,
  options: ChainCSSLoaderOptions
): Promise<{ css: string; classMap: Record<string, string> }> {
  if (!compileChainCSS._compiler) {
    const config: ChainCSSConfig = {
      atomic: { enabled: options.atomic ?? false },
      output: { minify: options.minify ?? false },
      verbose: options.verbose ?? false,
      silent: true,
    };
    compileChainCSS._compiler = new ChainCSSCompiler(config);
  }

  const compiler = compileChainCSS._compiler as ChainCSSCompiler;

  const tempDir = options.outputDir || '.chaincss-cache';
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
  }

  const hash = hashString(source);
  const tempPath = path.join(tempDir, `webpack-${hash}.chain.ts`);
  fs.writeFileSync(tempPath, source, 'utf8');

  try {
    const results = await compiler.compileFile(tempPath);
    let css = '';
    const classMap: Record<string, string> = {};

    for (const [name, result] of Object.entries(results)) {
      if (result.css) css += result.css + '\n';
      const className = Object.values(result.classMap)[0];
      if (className) classMap[name] = className;
    }

    return { css, classMap };
  } finally {
    try { fs.unlinkSync(tempPath); } catch {}
  }
}

compileChainCSS._compiler = null as ChainCSSCompiler | null;

// ============================================================================
// Loader
// ============================================================================

export default function chaincssLoader(this: LoaderContext, source: string): void {
  const callback = this.async();
  const options = this.getOptions() || {};

  this.cacheable(true);

  const mode = options.mode || (process.env.NODE_ENV === 'production' ? 'build' : 'runtime');
  const styleExports = extractStyleExports(source);

  if (options.verbose) {
    console.log(`[chaincss-loader] Processing ${path.basename(this.resourcePath)} in ${mode} mode`);
    console.log(`[chaincss-loader] Found exports: ${styleExports.map(e => e.name).join(', ')}`);
  }

  if (mode === 'runtime') {
    const code = generateRuntimeCode(source, styleExports, this.resourcePath, options);
    callback(null, code);
    return;
  }

  compileChainCSS(source, this.resourcePath, options)
    .then(({ css, classMap }) => {
      if (options.extractCSS && css) {
        const cssFileName = `${path.basename(this.resourcePath, path.extname(this.resourcePath))}.css`;
        this.emitFile(cssFileName, css);
      }

      const code = generateProductionCode(css, styleExports, this.resourcePath, options);
      callback(null, code);
    })
    .catch((err: Error) => {
      console.error(`[chaincss-loader] Error compiling ${this.resourcePath}:`, err.message);
      this.emitError(err);
      callback(err);
    });
}