// chaincss/src/plugins/webpack.ts

import path from 'path';
import { execSync } from 'child_process';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface ChainCSSLoaderOptions {
  /**
   * Mode: 'build' for production (zero-runtime), 'runtime' for development
   * @default process.env.NODE_ENV === 'production' ? 'build' : 'runtime'
   */
  mode?: 'build' | 'runtime';
  
  /**
   * Enable atomic CSS optimization
   * @default false
   */
  atomic?: boolean;
  
  /**
   * Enable CSS minification
   * @default process.env.NODE_ENV === 'production'
   */
  minify?: boolean;
  
  /**
   * Enable source maps
   * @default false
   */
  sourceMap?: boolean;
  
  /**
   * Output directory for compiled CSS
   * @default '.chaincss-cache'
   */
  outputDir?: string;
  
  /**
   * Verbose logging
   * @default false
   */
  verbose?: boolean;
}

interface LoaderContext {
  async: () => (err: Error | null, code?: string) => void;
  getOptions: () => ChainCSSLoaderOptions;
  resourcePath: string;
  context: string;
}

/**
 * Webpack loader for ChainCSS
 * Converts .chain.js / .chain.ts files to static CSS at build time
 */
export default function chaincssLoader(this: LoaderContext, source: string): void {
  const callback = this.async();
  const options = this.getOptions() || {};
  
  // Determine mode: default to 'build' in production, 'runtime' in development
  const mode = options.mode || (process.env.NODE_ENV === 'production' ? 'build' : 'runtime');
  
  // DEVELOPMENT MODE: Use runtime (fast iteration, but has runtime cost)
  if (mode === 'runtime') {
    if (options.verbose) {
      console.log(`[chaincss-loader] Runtime mode for ${this.resourcePath}`);
    }
    
    const styleNames = extractStyleNames(source);
    const code = `
      import { $, compile } from 'chaincss/runtime';
      const styles = (() => {
        ${source}
        return { ${styleNames} };
      })();
      export default styles;
    `;
    callback(null, code);
    return;
  }
  
  // PRODUCTION MODE: Build-time compilation (zero-runtime)
  try {
    if (options.verbose) {
      console.log(`[chaincss-loader] Build mode for ${this.resourcePath}`);
    }
    
    const tempFile = path.join(this.context, `.temp.${Date.now()}.chain.js`);
    const outputDir = options.outputDir || path.join(process.cwd(), '.chaincss-cache');
    
    // Ensure temp directory exists
    if (!fs.existsSync(path.dirname(tempFile))) {
      fs.mkdirSync(path.dirname(tempFile), { recursive: true });
    }
    
    // Write temp file
    fs.writeFileSync(tempFile, source, 'utf8');
    
    // Ensure output directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    
    // Build CLI command using your new compiler
    const chaincssCli = path.join(__dirname, '../cli/index.js');
    let cmd = `node ${chaincssCli} compile "${tempFile}" "${outputDir}"`;
    
    if (options.atomic) {
      cmd += ' --atomic';
    }
    if (options.minify) {
      cmd += ' --minify';
    }
    if (options.sourceMap) {
      cmd += ' --source-map';
    }
    
    if (options.verbose) {
      console.log(`[chaincss-loader] Executing: ${cmd}`);
    }
    
    // Execute compilation
    execSync(cmd, { stdio: options.verbose ? 'inherit' : 'pipe' });
    
    // Read generated CSS
    const baseName = path.basename(this.resourcePath, path.extname(this.resourcePath));
    const cssPath = path.join(outputDir, `${baseName}.css`);
    const jsPath = path.join(outputDir, `${baseName}.js`);
    
    let css = '';
    if (fs.existsSync(cssPath)) {
      css = fs.readFileSync(cssPath, 'utf8');
    }
    
    let classExports = '';
    if (fs.existsSync(jsPath)) {
      classExports = fs.readFileSync(jsPath, 'utf8');
    }
    
    // Clean up temp file
    fs.unlinkSync(tempFile);
    
    // Generate final code for Webpack
    // This exports both the class names AND injects CSS
    const code = `
      // Generated by ChainCSS Webpack Loader (Build Mode)
      // Zero-runtime CSS injection
      
      ${classExports}
      
      const css = ${JSON.stringify(css)};
      if (typeof document !== 'undefined') {
        const styleId = 'chaincss-${baseName}';
        let style = document.getElementById(styleId);
        if (!style) {
          style = document.createElement('style');
          style.id = styleId;
          style.setAttribute('data-chaincss', ${JSON.stringify(this.resourcePath)});
          document.head.appendChild(style);
        }
        style.textContent = css;
      }
      
      export default { ${extractStyleNames(source)} };
    `;
    
    callback(null, code);
    
  } catch (err: any) {
    console.error(`[chaincss-loader] Error compiling ${this.resourcePath}:`, err.message);
    callback(err);
  }
}

/**
 * Extract style variable names from source code
 * Matches: const styleName = $().block()
 */
function extractStyleNames(source: string): string {
  // Match const declarations that use $()
  const matches = source.match(/const\s+(\w+)\s*=\s*\$\(/g);
  if (!matches) return '';
  
  const names = matches.map(m => {
    const match = m.match(/const\s+(\w+)/);
    return match ? match[1] : '';
  }).filter(Boolean);
  
  return names.join(', ');
}