// ============================================================================
// FILE: src/plugins/webpack.ts
// ============================================================================

import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import { ChainCSSCompiler } from '../core/compiler.js';
import type { ChainCSSConfig } from '../core/types.js';
import { InspectorStore } from '../compiler/pipeline/inspector/store.js';
import { serializeForInspector } from '../compiler/pipeline/inspector/serializer.js';

export interface ChainCSSLoaderOptions {
  mode?: 'build' | 'runtime';
  atomic?: boolean;
  minify?: boolean;
  verbose?: boolean;
  extractCSS?: boolean;
  hmr?: boolean;
  outputDir?: string;
}

interface CompileResult {
  css: string;
  classMap: Record<string, string>;
  results: Record<string, any>;
}

interface LoaderContext {
  resourcePath: string;
  getOptions: () => ChainCSSLoaderOptions;
  async: () => (err: Error | null, result?: string, sourceMap?: any) => void;
  callback: (err: Error | null, result?: string, sourceMap?: any) => void;
  emitFile?: (name: string, content: string | Buffer, sourceMap?: any) => void;
}

const CHAIN_IMPORT_RE = /from\s+['"]chaincss['"]/;

const compilerCache = new Map<string, ChainCSSCompiler>();
function getCompiler(options: ChainCSSLoaderOptions): ChainCSSCompiler {
  const key = `${options.atomic ?? true}-${options.minify ?? false}`;
  if (!compilerCache.has(key)) {
    compilerCache.set(key, new ChainCSSCompiler({
      atomic: { enabled: options.atomic ?? true },
      output: { minify: options.minify ?? false },
      verbose: false,
      silent: true,
    } as ChainCSSConfig));
  }
  return compilerCache.get(key)!;
}

const globalInspectorStore = new InspectorStore();

export function clearInspectorData() {
  globalInspectorStore.clear();
  // optional: compilerCache.clear();
}
export function getInspectorData() {
  return globalInspectorStore.export({
    pipelinePreset: process.env.NODE_ENV === 'production' ? 'production' : 'development',
    compiledAt: new Date().toISOString()
  });
}

function ensureChainImport(source: string): string {
  if (CHAIN_IMPORT_RE.test(source)) return source;
  return `import { chain } from 'chaincss';\n${source}`;
}

async function compileChainCSS(source: string, resourcePath: string, options: ChainCSSLoaderOptions): Promise<CompileResult> {
  const compiler = getCompiler(options);
  const tempDir = path.resolve(options.outputDir || '.chaincss-webpack-tmp');
  if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir, { recursive: true });

  const tmp = path.join(tempDir, `wp-${Date.now()}-${crypto.randomBytes(8).toString('hex')}.chain.ts`);
  fs.writeFileSync(tmp, ensureChainImport(source), 'utf8');

  try {
    const results = await (compiler as any).compileFile(tmp);
    let css = '';
    const classMap: Record<string, string> = {};
    for (const [name, result] of Object.entries(results as Record<string, any>)) {
      if (result.css) css += result.css + '\n';
      const cn = Object.values(result.classMap || {})[0] as string | undefined;
      if (cn) classMap[name] = cn;
      if (result.inspector?.ir) {
        globalInspectorStore.addAll(serializeForInspector(
          result.inspector.ir,
          result.inspector.pipelineReport || [],
          result.inspector.diagnostics || [],
          resourcePath, name
        ));
      }
    }
    return { css, classMap, results: results as Record<string, any> };
  } finally {
    try { if (fs.existsSync(tmp)) fs.unlinkSync(tmp); } catch {}
  }
}

export default function chaincssLoader(this: LoaderContext, source: string): void {
  const callback = this.async();
  const options = this.getOptions?.() || {};
  compileChainCSS(source, this.resourcePath, options)
    .then(({ css, results }) => {
      const lines: string[] = ['// Auto-generated by ChainCSS Webpack Loader', '// DO NOT EDIT', ''];
      for (const [name, result] of Object.entries(results)) {
        const cn = Object.values(result.classMap || {})[0] as string | undefined;
        if (cn) lines.push(`export const ${name} = '${cn}';`);
        if (result.dynamic && typeof result.dynamic === 'object') {
          for (const [dName, dFn] of Object.entries(result.dynamic as Record<string, any>)) {
            // TODO: Compiler should return raw code string instead of live Function.
            // toString() works today because chain.dynamic() factories are self-contained,
            // but will break if they close over external vars. Fix in compiler v2.
            const code = typeof dFn === 'function' ? dFn.toString() : JSON.stringify(dFn);
            lines.push(`export const ${dName} = ${code};`);
          }
        }
      }
      if (!options.extractCSS && css.trim()) {
        lines.push(`if(typeof document!=='undefined'){var s=document.createElement('style');s.setAttribute('data-chaincss','');s.textContent=${JSON.stringify(css)};document.head.appendChild(s);}`);
      }
      if (options.extractCSS && css.trim()) {
        const cssFileName = path.basename(this.resourcePath).replace(/\.chain\.(ts|js)x?$/, '.css');
        this.emitFile?.(cssFileName, css);
      }
      callback(null, lines.join('\n'));
    })
    .catch((err) => callback(err));
}

// ============================================================================
// Webpack Plugin Companion
// ============================================================================
export class ChainCSSWebpackPlugin {
  private options: { outputJsonPath?: string };
  constructor(options: { outputJsonPath?: string } = {}) {
    this.options = options;
  }
  apply(compiler: any) {
    compiler.hooks.compile.tap('ChainCSSWebpackPlugin', () => {
      clearInspectorData();
    });
    compiler.hooks.emit.tapAsync('ChainCSSWebpackPlugin', (compilation: any, cb: any) => {
      const data = getInspectorData();
      const out = this.options.outputJsonPath || 'chaincss-ir.json';
      compilation.assets[out] = {
        source: () => JSON.stringify(data, null, 2),
        size: () => JSON.stringify(data, null, 2).length
      };
      cb();
    });
  }
}

// =========================================================================
//                        Usage : webpack.config.js
// =========================================================================
// 
//  const { ChainCSSWebpackPlugin } = require('chaincss/plugins/webpack');
//  module.exports = {
//    module: { 
//      rules: [{ test: /\.chain\.(ts|js)x?$/, use: 'chaincss/loader' }] 
//    },
//    plugins: [
//      new ChainCSSWebpackPlugin({ outputJsonPath: 'chaincss-ir.json' })
//    ]
//  }
//
// =========================================================================