// ============================================================================
// FILE: src/frameworks/build-tools/vite/index.ts
// ============================================================================

export type Plugin = any;
export type ViteDevServer = any;
import path from "path";
import fs from "fs";
import { cpus } from "os";
import crypto from "crypto";
import { promises as fsp } from "fs";
import { ChainCSSCompiler } from "@core/usecases/compiler.js";
import { formatCSS, ensureDir } from "@shared/utils/index.js";
import {
  DEFAULT_CONFIG,
  ENVIRONMENT_PRESETS,
} from "@shared/constants/index.js";
import type { ChainCSSPluginOptions } from "../types.js";
import { createPipeline } from "@compiler/pipeline/pipeline.js";
import { serializeForInspector } from "@compiler/pipeline/inspector/serializer.js";
import type { InspectorRule } from "@compiler/pipeline/inspector/types.js";
import { InspectorStore } from "@compiler/pipeline/inspector/store.js";
import {
  saveCompilerStateToDisk,
  restoreCompilerStateFromDisk,
} from "@compiler/pipeline/persistent-compiler.js";
const CHAIN_FILE_RE = /\.chain\.(ts|js)x?$/;
const TMP_MARKER = ".chaincss-tmp";
const isTmpFile = (p: string) => p.includes(TMP_MARKER);
const isGeneratedOutput = (p: string) =>
  p.endsWith(".css") || p.endsWith(".class.js");
function writeClassFileContent(
  classMap: Record<string, string>,
  dynamicMap: Record<string, any>,
) {
  const lines: string[] = [
    "// Auto-generated by ChainCSS Vite Plugin",
    "// DO NOT EDIT",
    "",
  ];
  for (const [name, className] of Object.entries(classMap)) {
    const dyn = dynamicMap[name];
    const hasDyn =
      dyn &&
      Object.keys(dyn).filter((k: string) => !k.startsWith("_")).length > 0;
    if (hasDyn) {
      lines.push(`export const ${name} = {`);
      lines.push(`  className: '${className}',`);
      lines.push(`  selectors: ['.${className}'],`);
      lines.push(`  dynamic: {`);
      for (const [k, v] of Object.entries(dyn as any)) {
        if (k.startsWith("_")) continue;
        if (typeof v === "function") {
          lines.push(`    "${k}": ${v.toString()},`);
        } else if (typeof v === "string" && v.trim().length > 0) {
          // Support pre-stringified function expressions from build pipelines
          lines.push(`    "${k}": ${v},`);
        }
      }
      lines.push(`  }`);
      lines.push(`};`);
    } else {
      lines.push(`export const ${name} = '${className}';`);
    }
  }
  return lines.join("\n");
}
export default function chaincssPlugin(
  options: ChainCSSPluginOptions = {},
): Plugin {
  const verbose = options.verbose ?? false;
  const silent = options.silent ?? false;
  const atomic = options.atomic ?? true;
  let compiler: ChainCSSCompiler;
  let root = "";
  let isProduction = false;
  let base = "/";
  const cssFileCache = new Map<string, string>();
  let _cachedCSS = "";
  const compiling = new Set<string>();
  const inspectorStore = new InspectorStore();
  function updateCSS(file: string, css: string) {
    cssFileCache.set(path.resolve(file), css);
    rebuildCache();
  }
  function removeCSS(file: string) {
    const absPath = path.resolve(file);
    cssFileCache.delete(absPath);
    inspectorStore.clearFileContext(absPath);
    rebuildCache();
  }
  function rebuildCache() {
    _cachedCSS = Array.from(cssFileCache.values()).filter(Boolean).join("\n");
  }
  function getCSS() {
    return _cachedCSS;
  }
  function log(msg: string) {
    if (!silent && verbose) console.log(`[ChainCSS] ${msg}`);
  }
  function logError(msg: string) {
    console.error(`[ChainCSS] ❌ ${msg}`);
  }
  function summary(msg: string) {
    if (!silent) console.log(`[ChainCSS] ${msg}`);
  }

  async function compileFile(chainPath: string, forcedContent?: string) {
    const absPath = path.resolve(chainPath);
    const source = forcedContent ?? fs.readFileSync(absPath, "utf8");
    inspectorStore.clearFileContext(absPath);
    try {
      const results = (await compiler.compileVirtualSource(
        source,
        absPath,
      )) as Record<string, any>;

      if (!results || typeof results !== "object" || Array.isArray(results)) {
        logError(
          `compileVirtualSource returned invalid result for ${path.basename(absPath)}`,
        );
        return { css: "", classMap: {}, dynamicMap: {} };
      }

      let css = "";
      const classMap: Record<string, string> = {};
      const dynamicMap: Record<string, any> = {};
      const rulesToRegister: InspectorRule[] = [];
      try {
        for (const [name, compileResult] of Object.entries(results) as [
          string,
          any,
        ][]) {
          if (compileResult?.css) css += compileResult.css + "\n";
          const className = Object.values(compileResult.classMap || {})[0] as
            string | undefined;
          if (className) classMap[name] = className;
          if ((compileResult as any)?.dynamic)
            dynamicMap[name] = (compileResult as any).dynamic;
          const inspector = compileResult?.inspector;
          if (inspector?.ir) {
            const pipelineReport = Array.isArray(inspector.pipelineReport)
              ? inspector.pipelineReport
              : Object.values(inspector.pipelineReport || {});

            const diagnostics = Array.isArray(inspector.diagnostics)
              ? inspector.diagnostics
              : Object.values(inspector.diagnostics || {});

            const rules = serializeForInspector(
              inspector.ir,
              pipelineReport,
              diagnostics,
              absPath,
              name,
            );

            if (rules) {
              if (Array.isArray(rules)) {
                rulesToRegister.push(...rules);
              } else {
                rulesToRegister.push(rules as InspectorRule);
              }
            }
          }
        }
      } catch (e) {
        console.error("[ChainCSS] Error iterating results:", e);
        console.error(
          "[ChainCSS] results type:",
          typeof results,
          "value:",
          results,
        );
        throw e;
      }
      if (rulesToRegister.length > 0) {
        inspectorStore.addAll(rulesToRegister);
        console.log(
          "[ChainCSS] IR rules collected:",
          rulesToRegister.length,
          "total:",
          inspectorStore.size,
        );
      } else {
        console.log("[ChainCSS] No IR data for:", absPath);
      }
      for (const [name, dyn] of Object.entries(dynamicMap)) {
        if (dyn && Object.keys(dyn).length > 0) {
          const className = classMap[name];
          if (className) {
            css += `\n.${className} {\n`;
            for (const [prop, fn] of Object.entries(
              dyn as Record<string, any>,
            )) {
              const kebabProp = prop.replace(/([A-Z])/g, "-$1").toLowerCase();
              css += `  ${kebabProp}: var(--${className}-${kebabProp});\n`;
            }
            css += "}\n";
          }
        }
      }
      const result = { css, classMap, dynamicMap };
      // Save to persistent cache
      if ((compiler as any).stateCache) {
        const sourceHash = crypto
          .createHash("md5")
          .update(source)
          .digest("hex");
        await (compiler as any).stateCache.setByHash(sourceHash, result);
      }
      return result;
    } catch (err) {
      logError(
        `Compilation failed on ${path.basename(absPath)}:\n${(err as Error).stack || (err as Error).message}`,
      );
      throw err;
    }
  }
  async function compileAllStyles() {
    if (!fs.existsSync(root)) return "";
    const cachePath = path.join(root, ".chaincss-cache");
    try {
      const stat = fs.statSync(cachePath);
      if (stat.isFile()) fs.unlinkSync(cachePath);
    } catch {}

    cssFileCache.clear();
    inspectorStore.clear();
    const chainFiles: string[] = [];

    const IGNORED_DIRS = new Set([
      "node_modules",
      "dist",
      ".git",
      ".vite",
      "build",
      "coverage",
      ".chaincss-cache",
    ]);

    function walk(dir: string) {
      let entries: fs.Dirent[];
      try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
      } catch {
        return;
      }
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (isTmpFile(fullPath) || isGeneratedOutput(fullPath)) continue;
        if (entry.isDirectory()) {
          if (IGNORED_DIRS.has(entry.name) || entry.name.startsWith(".")) continue;
          walk(fullPath);
        } else if (CHAIN_FILE_RE.test(entry.name)) {
          chainFiles.push(fullPath);
        }
      }
    }

    walk(root);

    if (!silent)
      summary(
        `Pre-compiling ${chainFiles.length} styling definition file(s)...`,
      );
    // Parallel compilation with concurrency limit
    const concurrency = Math.min(cpus().length, chainFiles.length || 1);
    let successCount = 0;
    let index = 0;

    async function worker() {
      while (index < chainFiles.length) {
        const i = index++;
        const file = chainFiles[i];
        try {
          const { css, classMap, dynamicMap } = await compileFile(file);
          if (css.trim()) {
            updateCSS(file, css);
            const cssPath = file.replace(CHAIN_FILE_RE, ".css");
            ensureDir(path.dirname(cssPath));
            await fsp.writeFile(cssPath, formatCSS(css, false), "utf8");
          }
          const classPath = file.replace(CHAIN_FILE_RE, ".class.js");
          const content = writeClassFileContent(classMap, dynamicMap);
          ensureDir(path.dirname(classPath));
          await fsp.writeFile(classPath, content, "utf8");
          successCount++;
        } catch (err) {
          logError(
            `Pre-compile failure on ${path.basename(file)}: ${(err as Error).message}`,
          );
        }
      }
    }

    const workers = Array.from({ length: concurrency }, () => worker());
    await Promise.all(workers);

    if (!silent)
      summary(
        `Pre-compiled ${successCount}/${chainFiles.length} style manifests successfully.`,
      );
    return getCSS();
  }
  function exportIRData() {
    return inspectorStore.export({
      pipelinePreset: isProduction ? "production" : "development",
      compiledAt: new Date().toISOString(),
    });
  }
  return {
    name: "chaincss",
    enforce: "pre",
    configResolved(config: any) {
      root = config.root;
      base = config.base || "/";
      isProduction = config.mode === "production";
      const preset = isProduction
        ? (ENVIRONMENT_PRESETS as any).production
        : (ENVIRONMENT_PRESETS as any).development;
      const dc = DEFAULT_CONFIG as any;
      const ps = preset as any;
      compiler = new ChainCSSCompiler({
        ...dc,
        ...ps,
        atomic: { ...dc.atomic, ...ps.atomic, enabled: atomic },
        tokens: options.tokens || dc.tokens,
        intents: (options as any).intents || dc.intents,
        output: {
          ...dc.output,
          minify: options.minify !== undefined ? options.minify : isProduction,
        },
        breakpoints: options.breakpoints || dc.breakpoints,
        verbose,
        silent,
      });
      const envPipeline = createPipeline(
        isProduction ? "production" : "default",
      );
      (compiler as any).pipeline = envPipeline;
      if (!silent) summary(`Pipeline Engine Hook Active (atomic: ${atomic})`);
    },
    async transform(_code: any, id: any) {
      if (!CHAIN_FILE_RE.test(id) || isTmpFile(id)) return null;
      const absPath = path.resolve(id);
      try {
        const { css, classMap, dynamicMap } = await compileFile(absPath);
        if (css.trim()) updateCSS(absPath, css);
        const code = writeClassFileContent(classMap, dynamicMap);
        return { code, map: { mappings: "" } as any };
      } catch (err) {
        logError(
          `Transform runtime failure on ${path.basename(id)}: ${(err as Error).message}`,
        );
        return null;
      }
    },
    async buildStart() {
      // Restore persistent compiler state for cold-start recovery
      if (
        compiler &&
        (compiler as any).isPersistentMode?.() &&
        (compiler as any).persistentCache
      ) {
        try {
          const projectHash = crypto
            .createHash("md5")
            .update(root)
            .digest("hex");
          const savedState = await restoreCompilerStateFromDisk(
            (compiler as any).persistentCache,
            projectHash,
          );
          if (savedState) {
            (compiler as any).setCompilerState?.(savedState);
            if (!silent)
              console.log("[ChainCSS] Restored compiler state from cache.");
          }
        } catch (e) {
          /* silent fail — will do full compilation */
        }
      }

      if (isProduction) {
        cssFileCache.clear();
        _cachedCSS = "";
        try {
          await compileAllStyles();
        } catch (e) {
          logError(
            `buildStart production capture failed: ${(e as Error).message}`,
          );
        }
      }
    },
    configureServer(devServer: ViteDevServer) {
      devServer.httpServer?.once("listening", async () => {
        try {
          await compileAllStyles();
        } catch (e) {
          logError((e as Error).message);
        }
        // Save compiler state after initial compilation
        if (
          (compiler as any).isPersistentMode?.() &&
          (compiler as any).persistentCache
        ) {
          const state = (compiler as any).getCompilerState?.();
          if (state) {
            const projectHash = crypto
              .createHash("md5")
              .update(root)
              .digest("hex");
            saveCompilerStateToDisk(
              state,
              (compiler as any).persistentCache,
              projectHash,
            ).catch(() => {});
          }
        }
      });
      const cssRoute = path.posix.join(base, "__chaincss.css");
      const clientRoute = path.posix.join(base, "@chaincss/client.js");
      const irRoute = path.posix.join(base, "__chaincss-ir.json");

      devServer.middlewares.use(cssRoute, (_req: any, res: any) => {
        res.setHeader("Content-Type", "text/css");
        res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
        res.end(getCSS() || "/* ChainCSS empty */");
      });

      devServer.middlewares.use(clientRoute, (_req: any, res: any) => {
        res.setHeader("Content-Type", "application/javascript");
        res.setHeader("Cache-Control", "no-cache");
        res.end(`
        import { createHotContext } from "/@vite/client";
        const STYLE_ID = 'chaincss-styles';
        const CSS_ENDPOINT = ${JSON.stringify(cssRoute)};
        const HOT_ENDPOINT = ${JSON.stringify(clientRoute)};
        function ensureStyleEl() {
          let el = document.getElementById(STYLE_ID);
          if (!el) {
            el = document.createElement('style');
            el.id = STYLE_ID;
            el.setAttribute('data-chaincss','');
            document.head.appendChild(el);
          }
          return el;
        }
        function applyCSS(css) {
          const el = ensureStyleEl();
          el.textContent = css;
        }
        fetch(CSS_ENDPOINT, { cache: 'no-store' }).then(r=>r.text()).then(applyCSS).catch(()=>{});
        const hot = createHotContext(HOT_ENDPOINT);
        hot.on('chaincss-update', (data) => {
          const url = CSS_ENDPOINT + '?v=' + (data?.timestamp || Date.now());
          fetch(url, { cache: 'no-store' }).then(r=>r.text()).then((css)=>{
            applyCSS(css);
            console.log('[ChainCSS] HMR updated', css.length + 'B');
          });
        });
        hot.accept();
      `);
      });

      devServer.middlewares.use(irRoute, (_req: any, res: any) => {
        res.setHeader("Content-Type", "application/json");
        res.setHeader("Cache-Control", "no-cache");
        res.end(JSON.stringify(exportIRData() || {}));
      });
      const handleFileChange = async (fp: string) => {
        if (isGeneratedOutput(fp)) return;
        if (!CHAIN_FILE_RE.test(fp) || isTmpFile(fp)) return;
        const abs = path.resolve(fp);
        if (path.relative(root, abs).startsWith("..")) return;
        if (compiling.has(abs)) return;
        compiling.add(abs);
        log(`Hot Module Reload Triggered: ${path.basename(abs)}`);
        try {
          // Check if the file actually changed vs cached state
          const source = fs.readFileSync(abs, "utf8");
          const sourceHash = crypto.createHash("md5").update(source).digest("hex");
          const previousHash = (compiler as any).compilerState?.fileExportHashes?.[abs]?.["__full_file__"];

          if (previousHash === sourceHash) {
            // File unchanged — skip compilation entirely
            log(`  ⚡ Skipped (unchanged): ${path.basename(abs)}`);
            return;
          }

          if ((compiler as any)?.invalidateFileCache)
            (compiler as any).invalidateFileCache(abs);
          const mod =
            devServer.moduleGraph.getModuleById(abs) ||
            (devServer.moduleGraph as any)
              .getModulesByFile?.(abs)
              ?.values?.()
              .next?.()?.value;
          if (mod) devServer.moduleGraph.invalidateModule(mod);
          const { css } = await compileFile(abs);
          updateCSS(abs, css);

          // Store hash for next comparison
          if ((compiler as any).compilerState) {
            const state = (compiler as any).compilerState;
            if (!state.fileExportHashes) state.fileExportHashes = {};
            if (!state.fileExportHashes[abs]) state.fileExportHashes[abs] = {};
            state.fileExportHashes[abs]["__full_file__"] = sourceHash;
          }

          devServer.ws.send({
            type: "custom",
            event: "chaincss-update",
            data: { timestamp: Date.now() },
          });
        } catch (err) {
          logError(
            `Watcher context update failed for ${path.basename(abs)}: ${(err as Error).message}`,
          );
        } finally {
          setTimeout(() => compiling.delete(abs), 200);
        }
      };
      devServer.watcher.on("change", handleFileChange);
      devServer.watcher.on("add", handleFileChange);
      devServer.watcher.on("unlink", (fp: string) => {
        if (isGeneratedOutput(fp)) return;
        if (CHAIN_FILE_RE.test(fp) && !isTmpFile(fp)) {
          removeCSS(fp);
          // Clean up generated artifacts
          const classFile = fp.replace(CHAIN_FILE_RE, ".class.js");
          const cssFile = fp.replace(CHAIN_FILE_RE, ".css");
          try {
            if (fs.existsSync(classFile)) fs.unlinkSync(classFile);
          } catch {}
          try {
            if (fs.existsSync(cssFile)) fs.unlinkSync(cssFile);
          } catch {}
          devServer.ws.send({
            type: "custom",
            event: "chaincss-update",
            data: { timestamp: Date.now() },
          });
        }
      });
      devServer.watcher.on("unlinkDir", (dirPath: string) => {
        const absDir = path.resolve(dirPath);
        let removedAny = false;

        for (const cachedFile of cssFileCache.keys()) {
          if (cachedFile.startsWith(absDir)) {
            cssFileCache.delete(cachedFile);
            inspectorStore.clearFileContext(cachedFile);
            removedAny = true;
          }
        }

        if (removedAny) {
          rebuildCache();
          devServer.ws.send({
            type: "custom",
            event: "chaincss-update",
            data: { timestamp: Date.now() },
          });
        }
      });
    },
    async handleHotUpdate(ctx: any) {
      const filePath = path.resolve(ctx.file);
      if (
        isGeneratedOutput(filePath) ||
        !CHAIN_FILE_RE.test(filePath) ||
        isTmpFile(filePath)
      )
        return;
      if (compiling.has(filePath)) return;
      compiling.add(filePath);
      log(`Direct Buffer Update Intercepted: ${path.basename(filePath)}`);
      try {
        // Check if the file actually changed vs cached state
        const source = fs.readFileSync(filePath, "utf8");
        const sourceHash = crypto.createHash("md5").update(source).digest("hex");
        const previousHash = (compiler as any).compilerState?.fileExportHashes?.[filePath]?.["__full_file__"];

        if (previousHash === sourceHash) {
          log(`  ⚡ Skipped (unchanged): ${path.basename(filePath)}`);
          return [];
        }

        const mod = ctx.server.moduleGraph.getModuleById(filePath);
        if (mod) ctx.server.moduleGraph.invalidateModule(mod);
        if ((compiler as any)?.invalidateFileCache)
          (compiler as any).invalidateFileCache(filePath);
        const { css } = await compileFile(filePath);
        updateCSS(filePath, css);

        // Store hash for next comparison
        if ((compiler as any).compilerState) {
          const state = (compiler as any).compilerState;
          if (!state.fileExportHashes) state.fileExportHashes = {};
          if (!state.fileExportHashes[filePath]) state.fileExportHashes[filePath] = {};
          state.fileExportHashes[filePath]["__full_file__"] = sourceHash;
        }

        ctx.server.ws.send({
          type: "custom",
          event: "chaincss-update",
          data: { timestamp: Date.now() },
        });
        return ctx.modules.filter(
          (m: any) => m.id === filePath || m.file === filePath,
        );
      } catch (err) {
        logError(`Inline HMR processor failed: ${(err as Error).message}`);
        return [];
      } finally {
        setTimeout(() => compiling.delete(filePath), 200);
      }
    },
    async generateBundle() {
      const ir = exportIRData();
      if (ir) {
        this.emitFile({
          type: "asset",
          fileName: "assets/chaincss-ir.json",
          source: JSON.stringify(ir),
        });
      }

      // CSS emission is independent of IR data — always emit if CSS exists
      const cssContent = getCSS();
      if (cssContent) {
        this.emitFile({
          type: "asset",
          fileName: "assets/chaincss.css",
          source: formatCSS(cssContent, false),
        });
      }
    },
    async buildEnd() {
      if (
        compiler &&
        (compiler as any)?.isPersistentMode?.() &&
        (compiler as any)?.persistentCache
      ) {
        const state = (compiler as any).getCompilerState?.();
        if (state) {
          try {
            const projectHash = crypto
              .createHash("md5")
              .update(root)
              .digest("hex");
            await saveCompilerStateToDisk(
              state,
              (compiler as any).persistentCache,
              projectHash,
            );
          } catch {}
        }
      }
    },
    resolveId(id: string) {
      if (id === "virtual:chaincss.css" || id === "\0virtual:chaincss.css") {
        return "\0virtual:chaincss.css";
      }
      if (
        id === "virtual:chaincss-manifest" ||
        id === "\0virtual:chaincss-manifest"
      ) {
        return "\0virtual:chaincss-manifest";
      }
      return null;
    },
    load(id: string) {
      if (id === "\0virtual:chaincss.css") {
        return getCSS() || "/* ChainCSS empty */";
      }
      if (id === "\0virtual:chaincss-manifest") {
        const ir = exportIRData();
        return `export const atomicMap = {};\nexport const ir = ${JSON.stringify(ir)};\nexport default { atomicMap, ir };`;
      }
      return null;
    },
    transformIndexHtml() {
      if (isProduction) {
        return [
          {
            tag: "link",
            attrs: {
              rel: "stylesheet",
              href: `${base}assets/chaincss.css`,
              "data-chaincss": "",
            },
            injectTo: "head",
          },
        ];
      }
      return [
        {
          tag: "style",
          attrs: { id: "chaincss-styles", "data-chaincss": "" },
          children: "/* ChainCSS Dev Server Hot Injection Hook */",
          injectTo: "head",
        },
        {
          tag: "script",
          attrs: { type: "module", src: path.posix.join(base, "@chaincss/client.js") },
          injectTo: "head",
        },
      ];
    },
  };
}
