// ============================================================================
// FILE: src/compiler/pipeline/ir/types.ts
// ============================================================================

import type { PassMetadata } from "./metadata.js";

export type IRNodeId = string;

/** Graph representation of the IR */
export interface IRGraph {
  nodes: Map<IRNodeId, IRRule>;
  edges: IRGraphEdge[];
  rootNodes: IRNodeId[];
  leafNodes: IRNodeId[];
}

export interface IRGraphEdge {
  from: IRNodeId;
  to: IRNodeId;
  type:
    | "overrides"
    | "references"
    | "extends"
    | "derives"
    | "contrasts"
    | "contains"
    | "animates"
    | "layers";
  metadata?: Record<string, unknown>;
}

/** Source location for debugging and source maps */
export interface SourceLocation {
  file?: string;
  line?: number;
  column?: number;
  /** Component name (e.g., React component that generated this style) */
  component?: string;
}

/** A single CSS declaration (property: value) */
export interface IRDeclaration {
  id: IRNodeId;
  property: string;
  value: string | number;
  important?: boolean;
  source?: SourceLocation;
  /** Transform history — who modified this and why */
  history: IRTransformRecord[];
  /** Metadata from passes */
  meta: IRDeclarationMeta;
}

// ============================================================================
// Parsed Value Support (v2.10+)
// ============================================================================

/** Structured representation of a CSS declaration value. */
export type ParsedValue =
  | { kind: "dimension"; value: number; unit: string }
  | { kind: "number"; value: number }
  | { kind: "keyword"; value: string }
  | { kind: "color"; hex: string }
  | { kind: "function"; name: string; args: ParsedValue[] }
  | { kind: "list"; items: ParsedValue[] }
  | { kind: "raw"; value: string };

/** Metadata attached to IR declarations */
export interface IRDeclarationMeta {
  /** Structured representation parsed out from raw text */
  parsed?: ParsedValue;
  /** Marked as atomic utility class */
  atomic?: boolean;
  /** Generated by an internal pass (not user-authored) */
  generated?: boolean;
  /** Allow extensions by future passes */
  [key: string]: unknown;
  ast?: import("./css-ast.js").CSSValueNode;
}

/**
 * Metadata attached to IR rules.
 *
 * @deprecated Flat fields like `atomic`, `component`, `framework` are migrating
 * to the namespaced `passMeta` structure. Use `rule.passMeta.optimization.atomic`
 * instead of `rule.meta.atomic`, `rule.passMeta.analysis.component` instead of
 * `rule.meta.component`, etc. The old flat fields remain for backward compat
 * during the migration window.
 */
export interface IRRuleMeta {
  /** Component name that generated this rule */
  component?: string;
  /** Framework that generated this rule */
  framework?: "react" | "vue" | "svelte" | "solid" | "angular";
  /** @deprecated Use rule.passMeta.optimization.atomic.isAtomic instead */
  atomic?: boolean;
  /** Allow extensions */
  [key: string]: unknown;
  /** Graph dependencies — rule IDs that this rule depends on */
  dependencies?: IRNodeId[];
  /** Graph dependents — rule IDs that depend on this rule */
  dependents?: IRNodeId[];
}

export type DetectedFeature =
  | "constraints"
  | "semantic-tokens"
  | "intents"
  | "at-rules"
  | "pseudo-classes"
  | "declarations"
  | "viewport-units"
  | "large-fixed"
  | "flexbox-grid"
  | "css-grid"
  | "animations"
  | "keyframes"
  | "custom-properties"
  | "core";

/** A CSS rule (selector + declarations + nested rules) */
export interface IRRule {
  id: IRNodeId;
  parentId?: IRNodeId;
  selector: string;
  declarations: IRDeclaration[];
  pseudoClasses: IRPseudoClass[];
  atRules: IRAtRule[];
  nestedRules: IRRule[];
  conditions: IRCondition[];
  /** Incremental: dirty flag — optional for backward compat with cached IR */
  _dirty?: boolean;
  /** Flat metadata (deprecated fields migrating to passMeta) */
  meta: IRRuleMeta;
  /**
   * Namespaced pass-owned metadata.
   * Each pass writes to its own namespace — no cross-pass pollution.
   *
   * Examples:
   * - rule.passMeta.analysis.semantic  (was rule.meta._semantic)
   * - rule.passMeta.analysis.constraints (was rule.meta._constraints)
   * - rule.passMeta.analysis.intents   (was rule.meta._intent)
   * - rule.passMeta.optimization.atomic (was rule.meta.atomic)
   * - rule.passMeta.analysis.component  (was rule.meta.component)
   * - rule.passMeta.analysis.framework  (was rule.meta.framework)
   */
  passMeta?: PassMetadata;
  isDead: boolean;
  specificity: number;
  hash: string;
  source: SourceLocation;
  history: IRTransformRecord[];
}

/** Pseudo-class block (hover, focus, etc.) */
export interface IRPseudoClass {
  id: IRNodeId;
  parentId: IRNodeId;
  name: string; // 'hover', 'focus', 'active', etc.
  declarations: IRDeclaration[];
  source: SourceLocation;
  history: IRTransformRecord[];
}

/** Individual frame block inside a @keyframes container */
export interface IRKeyframeFrame {
  id: IRNodeId;
  /** Frame selector stops: e.g., '0%', '50%', 'from', 'to' */
  keyText: string;
  declarations: IRDeclaration[];
  source: SourceLocation;
}

/** At-rule block (media, keyframes, supports, etc.) */
export interface IRAtRule {
  id: IRNodeId;
  parentId?: IRNodeId;
  type:
    "media" | "keyframes" | "font-face" | "supports" | "container" | "layer";
  query?: string; // Media query text (e.g. '(min-width: 768px)')
  name?: string; // Keyframes identifier name (e.g. 'fade-in')
  declarations: IRDeclaration[];
  nestedRules: IRRule[];
  keyframes?: IRKeyframeFrame[]; // Explicit container for Phase 2 animation frames
  source: SourceLocation;
  history: IRTransformRecord[];
}

/** CSS if() conditional statements */
export interface IRCondition {
  id: IRNodeId;
  property: string;
  variable: string;
  conditions: Record<string, string | number>;
  defaultValue: string | number;
  source: SourceLocation;
}

/** Transform record — who touched this node and why. */
export interface IRTransformRecord {
  pass: string; // e.g., 'intent-engine', 'math-engine'
  action: string; // e.g., 'corrected-value', 'eliminated'
  timestamp: number;
  previous?: unknown; // Snapshot value before transform
  reason?: string; // Explanation text
}

/** The complete consolidated IR tree */
export interface StyleIR {
  id: string;
  rules: IRRule[];
  diagnostics: IRDiagnostic[];
  meta: {
    version: string;
    createdAt: number;
    sourceFiles: string[];
    passCount: number;
    passes: string[];
    /** Incremental: rules changed since last compilation */
    dirtyRules: number;
    /** Incremental: timestamp of this compilation */
    compiledAt: number;
  };
  /** Optional graph representation (nodes + edges) */
  graph?: IRGraph;
}

/** Diagnostic attached to an IR node */
export interface IRDiagnostic {
  id: IRNodeId;
  nodeId: IRNodeId;
  severity: "error" | "warning" | "info" | "hint";
  message: string;
  suggestion?: string;
  pass: string;
}

// ============================================================================
// Incremental Compilation Support (v2.9+)
// ============================================================================

export interface IRDirtyFlag {
  dirty: boolean;
  changedAt: number;
}

// ============================================================================
// Legacy Pass System (v3.0 — use Pipeline + CompilerContext instead)
// ============================================================================

/** Legacy IR pass — function that transforms IR in place */
export type IRPass = (ir: StyleIR) => StyleIR;

export type IRKeyframe = IRKeyframeFrame;
