// src/compiler/pipeline/ir/types.ts
/** Core IR types for ChainCSS intermediate representation. */

export type IRNodeId = string;

/** Source location for debugging and source maps */
export interface SourceLocation {
  file?: string;
  line?: number;
  column?: number;
  /** Component name (e.g., React component that generated this style) */
  component?: string;
}

/** A single CSS declaration (property: value) */
export interface IRDeclaration {
  id: IRNodeId;
  property: string;
  value: string | number;
  parsed?: ParsedValue;
  important?: boolean;
  source?: SourceLocation;
  /** Transform history — who modified this and why */
  history: IRTransformRecord[];
  /** Metadata from passes */
  meta: IRDeclarationMeta;
}

// ============================================================================
// Parsed Value Support (v2.10+)
// ============================================================================

/**
 * Structured representation of a CSS declaration value.
 * Stored in IRDeclaration.meta.parsed by the parser.
 * Used by Pipeline.detectFeatures() to avoid brittle string matching.
 */
export type ParsedValue =
  | { kind: 'dimension'; value: number; unit: string }
  | { kind: 'number'; value: number }
  | { kind: 'keyword'; value: string }
  | { kind: 'color'; hex: string }
  | { kind: 'function'; name: string; args: ParsedValue[] }
  | { kind: 'list'; items: ParsedValue[] }
  | { kind: 'raw'; value: string };

/**
 * Features that can be detected from IR structure.
 * Used by Pipeline.shouldRun() to skip irrelevant passes.
 */

// ============================================================================
// Metadata interfaces — replaces Record<string, unknown> for type safety
// ============================================================================

/** Metadata attached to IR declarations */
export interface IRDeclarationMeta {
  /** Parsed value from the parser (v2.10+) */
  parsed?: ParsedValue;
  /** Marked as atomic utility class */
  atomic?: boolean;
  /** Generated by a pass (not user-authored) */
  generated?: boolean;
  /** Allow extensions by future passes */
  [key: string]: unknown;
}

/** Metadata attached to IR rules */
export interface IRRuleMeta {
  /** Component name that generated this rule */
  component?: string;
  /** Framework that generated this rule */
  framework?: 'react' | 'vue' | 'svelte' | 'solid' | 'angular';
  /** Marked as atomic utility */
  atomic?: boolean;
  /** Allow extensions */
  [key: string]: unknown;
}

export type DetectedFeature =
  | 'constraints'
  | 'semantic-tokens'
  | 'intents'
  | 'at-rules'
  | 'pseudo-classes'
  | 'declarations'
  | 'viewport-units'
  | 'large-fixed'
  | 'flexbox-grid'
  | 'css-grid'
  | 'animations'
  | 'custom-properties'
  | 'core';

/** A CSS rule (selector + declarations + nested rules) */
export interface IRRule {
  id: IRNodeId;
  selector: string;
  declarations: IRDeclaration[];
  pseudoClasses: IRPseudoClass[];
  atRules: IRAtRule[];
  nestedRules: IRRule[];
  /** Conditional if() expressions */
  conditions: IRCondition[];
  /** Incremental: dirty flag for selective recompilation */
  _dirty: boolean;
  meta: IRRuleMeta;
  /** Dead code flag — set by optimizer passes */
  isDead: boolean;
  /** Specificity — set by graph pass */
  specificity: number;
  /** Content hash for deduplication */
  hash: string;
  source: SourceLocation;
  history: IRTransformRecord[];
}

/** Pseudo-class block (hover, focus, etc.) */
export interface IRPseudoClass {
  id: IRNodeId;
  name: string; // 'hover', 'focus', 'active', etc.
  declarations: IRDeclaration[];
  source: SourceLocation;
  history: IRTransformRecord[];
}

/** At-rule block (media, keyframes, supports, etc.) */
export interface IRAtRule {
  id: IRNodeId;
  type: 'media' | 'keyframes' | 'font-face' | 'supports' | 'container' | 'layer';
  query?: string;
  name?: string;
  declarations: IRDeclaration[];
  nestedRules: IRRule[];
  source: SourceLocation;
  history: IRTransformRecord[];
}

/** CSS if() conditional */
export interface IRCondition {
  id: IRNodeId;
  property: string;
  variable: string;
  conditions: Record<string, string | number>;
  defaultValue: string | number;
  source: SourceLocation;
}

/** Transform record — who touched this node and why */
/** 
 * Transform record — who touched this node and why.
 * @note History arrays grow unbounded. Debug builds may truncate.
 */
export interface IRTransformRecord {
  pass: string;       // e.g., 'intent-engine', 'math-engine', 'graph-compiler'
  action: string;     // e.g., 'corrected-value', 'resolved-unit', 'eliminated'
  timestamp: number;
  previous?: unknown;    // value before transform
  reason?: string;    // human-readable explanation
}

/** The full IR tree */
export interface StyleIR {
  id: string;
  rules: IRRule[];
  diagnostics: IRDiagnostic[];
  meta: {
    version: string;
    createdAt: number;
    sourceFiles: string[];
    passCount: number;
    passes: string[];
    /** Incremental: rules changed since last compilation */
    dirtyRules: number;
    /** Incremental: timestamp of this compilation */
    compiledAt: number;
  };
}

/** Diagnostic attached to an IR node */
export interface IRDiagnostic {
  id: IRNodeId;
  nodeId: IRNodeId;
  severity: 'error' | 'warning' | 'info' | 'hint';
  message: string;
  suggestion?: string;
  pass: string;
}

// ============================================================================
// Incremental Compilation Support (v2.9+)
// ============================================================================

/** Tracks whether a node has been modified since last compilation */
export interface IRDirtyFlag {
  /** Node has been added or modified since last run */
  dirty: boolean;
  /** Timestamp of last modification */
  changedAt: number;
}
